#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`


runApplication -l log.blockMesh.solid blockMesh -region solid
runApplication -l log.setSet.solid setSet -region solid -batch solid.setSet
runApplication -l log.setsToZones.solid setsToZones -region solid -noFlipMap

runApplication -l log.blockMesh blockMesh 
runApplication -l log.setSet setSet -batch fluid.setSet
runApplication -l log.setsToZones setsToZones -noFlipMap



runApplication conjugateHeatFoam

source postProcessDsip

runApplication -l log.sample sample 
runApplication -l log.sample.solid sample -region solid 

cat sets/0.07/TatYLine_T.xy >>  TatYLine_T.xy
cat sets/solid/0.07/TatYLine_T.xy >>  TatYLine_T.xy

# ----------------------------------------------------------------- end-of-file

