#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
\rm -f constant/cavity/polyMesh/boundary
\rm -rf constant/cavity/polyMesh/[c-z]*

\rm -f constant/solid/polyMesh/boundary
\rm -rf constant/solid/polyMesh/[c-z]*

\rm -f *xls
